name: android

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [21, 24, 26, 29]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
        env:
          API_LEVEL: ${{ matrix.api-level }}
